import RecoilRootWrapper from './recoil/RecoilRootWrapper';
import './globals.css';
import type { Metadata } from 'next';
import Layout from './components/Layout/Layout';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sun Co.',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <RecoilRootWrapper>
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </RecoilRootWrapper>
    </html>
  );
}
